apis/urls.py
from django.urls import path
from .views import UserCreateView, UserLoginView, UserLogoutView, ContentCreateView, RelationCreateView, RelationDeleteView, UserInfoGetView


urlpatterns = [
    # 인증 api
    path('v1/users/create/', UserCreateView.as_view(), name='apis_v1_user_create'),
    path('v1/users/login/', UserLoginView.as_view(), name='apis_v1_user_login'),
    path('v1/users/logout/', UserLogoutView.as_view(), name='apis_v1_user_logout'),
    path('v1/users/get/', UserInfoGetView.as_view(), name='apis_v1_user_get'),

    # 게시물 api
    path('v1/contents/create/', ContentCreateView.as_view(), name='apis_v1_content_create'),

    # 팔로우 api
    path('v1/relations/create/', RelationCreateView.as_view(), name='apis_v1_relation_create'),
    path('v1/relations/delete/', RelationDeleteView.as_view(), name='apis_v1_relation_delete'),
]

instagram/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

contents/models.py
import os
import uuid

from django.db import models
from django.contrib.auth.models import User

# Create your models here.
# 다른 클래스에 기본으로 상속되는 base모델.
class BaseModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


# Content 모델 생성
class Content(BaseModel):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()

    class Meta:
        ordering = ['-created_at']


# 사용자가 업로드 한 이미지의 네임을 그대로 사용하지 않고, 16자리의 고유한 아이디를 생성. --> uuid
def image_upload_to(instance, filename):
    ext = filename.split('.')[-1]
    return os.path.join(instance.UPLOAD_PATH, "%s.%s" %(uuid.uuid4(), ext))


# Image 모델 생성
class Image(BaseModel):
    UPLOAD_PATH = 'user-upload'

    content = models.ForeignKey(Content, on_delete=models.CASCADE)
    image = models.ImageField(upload_to=image_upload_to)
    order = models.SmallIntegerField() # 이미지 순서를 위한 필드

    class Meta:
        unique_together = ['content', 'order']
        ordering = ['order']


# 팔로우 관계 모델
class FollowRelation(BaseModel):
    follower = models.OneToOneField(User, on_delete=models.CASCADE, related_name='follower')
    followee = models.ManyToManyField(User, related_name='followee')

templates/base.html
<!DOCTYPE html>

{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Instagram{% endblock %}</title>

    <!--    Bootstrap-->
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'css/register.css' %}" type="text/css">

    <script src="https://kit.fontawesome.com/26a062b285.js" crossorigin="anonymous"></script>

    {% block head %}
    {% endblock %}

</head>
<body>
{% block body %}
{% endblock %}
</body>
</html>

templates/header.html
{% extends 'base.html' %}

<!--navbar-->
{% block body %}
<nav class="instagram-nav navbar navbar-expand-lg navbar-light bg-white">
    <a class="navbar-border text-danger col-sm-8" href="/"><b>Instagram</b></a>
    <div class="collapse-nav collapse navbar-collapse col-sm-4" id="navbarText" style="display-block !important; text-align: right;">
        <span class="navbar-text sol-sm-3">
            {{ request.user }}
        </span>
        <span class="navbar-text col-sm-3">
            <a href="{% url 'relation' %}">친구목록</a>
        </span>
        <span class="navbar-text col-sm-3">
            <a href="javascript:void(0); id=logout">로그아웃</a>
        </span>
    </div>
</nav>
{% endblock %}

templates/home.html
{% extends 'base.html' %}

{% load static %}

{% block head %}
<!--DropZone script-->
<script src="https://unpkg.com/dropzone@6.0.0-beta.1/dist/dropzone-min.js"></script>
<link href="https://unpkg.com/dropzone@6.0.0-beta.1/dist/dropzone.css" rel="stylesheet" type="text/css"/>
<!--style.css-->
<link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css">
{% endblock %}

{% block body %}

<nav class="instagram-nav navbar navbar-expand-lg navbar-light bg-white">
    <a class="navbar-border text-danger col-sm-8" href="/"><b>Instagram</b></a>
    <div class="collapse-nav collapse navbar-collapse col-sm-4" id="navbarText">
        <span class="navbar-text sol-sm-3">
            {{ request.user }}
        </span>
        <span class="navbar-text col-sm-3">
            <a href="{% url 'relation' %}">친구목록</a>
        </span>
        <span class="navbar-text col-sm-3">
            <a href="#">로그아웃</a>
        </span>
    </div>
</nav>

<script src="https://code.jquery.com/jquery-3.4.1.js" integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU="
        crossorigin="anonymous"></script>
<!--Dropzone-->
<script src="https://unpkg.com/dropzone@6.0.0-beta.1/dist/dropzone-min.js"></script>
<link href="https://unpkg.com/dropzone@6.0.0-beta.1/dist/dropzone.css" rel="stylesheet" type="text/css"/>


<!--Content-->
<br>
<br>
<div id="formContainer">
    <form action="{% url 'apis_v1_content_create' %}" class="dropzone" id="uploader"
          style="background-color:whitesmoke;">
        <div class="dz-message" data-dz-message><span>드래그 드랍하거나 클릭하여 이미지 선택</span></div>
        <div class="fallback">
            <input name="file" type="file">
        </div>
    </form>
    <div class="form-group">
        <label>아래에 글을 입력해주세요.</label>
        <textarea class="form-control rounded-0" id="text" rows="3"></textarea>
    </div>
    <div style="text-align: right;">
        <button type="button" class="btn btn-success" id="upload">작성하기</button>
    </div>
</div>

<br>
<br>
{% for content in contents %}
{% for image in content.image_set.all %}
<div class="content">
    <div class="post">
        <div class="user-block">
            <h5 class="text-info left-things">{{ content.user.username }}</h5>
            <img class="img-info img-circle img-bordered-sm" src="{{ image.image.url }}" alt="User Image">
            {% endfor %}
            <div>
                <span class="username left-things">
                    <a href="#" class="text-info">{{ content.user.username }}</a>
                    <a href="#" class="pull-right btn-box-tool"><i class="fa fa-times"></i></a>
                </span>
            </div>
            <p>{{ content.text }}</p>
        </div>
    </div>
</div>
<br>
{% endfor %}


<!--로그아웃 스크립트-->
<script>
    $(document).ready(function () {
    $('#logout').click(function() {
        $.get('/apis/v1/users/logout/', {}, function() {
            location.reload();
        })
});
});

</script>

<script>
    Dropzone.autoDiscover = false;

    var dropZoneUploader = new Dropzone('form#uploader', {
    init: function () {
        var dropzone = this;

        $('#upload').click(function () {
            dropZoneUploader.processQueue();
        });

        dropzone.on('sending', function(file, xhr, formData) {
        formData.append('text', $('#text').val());
        });
    },
    parallelUploads: 10,
    autoProcessQueue: false,
    type: 'POST',
    success: function () {
        location.reload();
    },
    error: function(e) {
        console.log(e)
        alert('에러가 발생했습니다. 다시 시도해주세요.');
    },
    acceptedFiles: '.jpeg,.jpg,.png,.gif',
    uploadMultiple: true,
    });

</script>
{% endblock %}

templates/login.html
{% extends 'base.html' %}

{% block body %}
<div id="login">
    <div class="container">
        <br>
        <h3 class="d-flex justify-content-center text-danger">Login</h3><br>
        <div class="form-group col-md-6">
            <label for="username" class="text-danger">Username:</label><br>
            <input type="text" name="username" id="username" class="form-control">
        </div>
        <div class="form-group col-md-6">
            <label for="password" class="text-danger">Password:</label><br>
            <input type="password" name="password" id="password" class="form-control">
        </div>
        <br>
        <div class="form-group col-md-6">
            <div class="row">
                <input type="submit" id="loginButton" class="form-control btn btn-danger" value="Login">
            </div>
        </div>
        <br>
        <div class="form-group col-md-6">
            <div class="row">
                <a href="{% url 'register' %}" class="form-control btn btn-outline-danger">Register here!</a>
            </div>
        </div>

    </div>
</div>

<!--Jquery-->
<script src="https://code.jquery.com/jquery-3.6.0.js"
        integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk="
        crossorigin="anonymous"></script>

<!--<script src="https://code.jquery.com/jquery-3.4.1.js" integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU="-->
<!--        crossorigin="anonymous"></script>-->

<!--로그인 스크립트-->
<script>
    $(document).ready(function () {
    $('#loginButton').click(function() {
        $.post('/apis/v1/users/login/', {'username': $('#username').val(), 'password': $('#password').val()}, function() {
            window.location = '/';
        }).fail(function(data) {
            alert(data.responseJSON.message);
        });
});
});

</script>
{% endblock %}

templates/register.html
{% extends 'base.html' %}

{% block body %}
<div id="register">
    <div class="container">
        <br>
        <h3 class="d-flex justify-content-center text-danger text-danger">Sign Up</h3>
        <div class="form-group col-md-6">
            <label for="username" class="text-danger">Username:</label><br>
            <input type="text" name="username" id="username" class="form-control">
        </div>
        <div class="form-group col-md-6">
            <label for="email" class="text-danger">Email:</label><br>
            <input type="email" name="email" id="email" class="form-control">
        </div>
        <div class="form-group col-md-6">
            <label for="password" class="text-danger">Password:</label><br>
            <input type="password" name="password" id="password" class="form-control">
        </div>
        <br>
        <div class="form-group col-md-6">
            <div class="row">
                <input type="submit" id="registerButton" class="form-control btn btn-danger" value="Sign Up">
            </div>
        </div>

    </div>
</div>

<!--Jquery 3.6-->
<!--<script src="https://code.jquery.com/jquery-3.6.0.js"-->
<!--        integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk="-->
<!--        crossorigin="anonymous"></script>-->
<!--Jquery 3.4.1-->
<script src="https://code.jquery.com/jquery-3.4.1.js" integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU="
        crossorigin="anonymous"></script>

<!--회원가입 스크립트-->
<script>
    $(document).ready(function () {
    $('#registerButton').click(function() {
        $.post('/apis/v1/users/create/', {'username': $('#username').val(), 'email': $('#email').val(), 'password': $('#password').val()}, function() {
            alert('회원가입을 축하합니다.');
            window.location = {% url 'login' %};
        }).fail(function(data) {
            alert(data.responseJSON.message);
        });
});
});


</script>

{% endblock %}

templates/relation.html
{% include 'header.html' %}

{% block head %}
<link href="https://unpkg.com/dropzone@6.0.0-beta.1/dist/dropzone.css" rel="stylesheet" type="text/css"/>
{% endblock %}

{% block body %}

<div class="all" style="width :600px; margin:0 auto;">

    <p>사용자 찾기</p>
    <input type="text" id="searchUserName" placeholder="Enter username..">
    <button id="search" class="btn-outline-success">검색</button>
    <p><b id="searchResult"></b>
        <span id="searchFollow" style="display:none;">-<button></button></span></p>
    <hr>
    <hr>

    <h4>날 팔로우하는 사람</h4>
    {% if followers %}
    <ul class="list-group">
        {% for myfollower in followers %}
        <li class="list-group-item col-md-6">
            {{ myfollower.follower.username }}
            <!--나를 팔로우하는 사람을 내가 팔로우하지 않은 경우-->
            {% if myfollower.follower.id in followees_ids %}
            -
            <button class="unfollow btn btn-outline-danger" data-user-id="{{ myfollower.follower.id }}">언팔로우</button>

            {% else %}
            -
            <button class="follow btn btn-outline-success" data-user-id="{{ myfollower.follower.id }}">팔로우</button>
            {% endif %}
        </li>
        {% endfor %}
    </ul>
    {% endif %}

    <hr>

    <h4>내가 팔로우하는 사람들</h4>
    {% if followees %}
    <ul class="list-group">
        {% for user in followees %}
        <li class="list-group-item col-md-6">{{user.username}} -
            <button class="unfollow btn btn-outline-danger" data-user-id="{{user.id}}">언팔로우</button>
        </li>
        {% endfor %}
    </ul>
    {% endif %}

</div>

<script src="https://code.jquery.com/jquery-3.4.1.js" integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU="
        crossorigin="anonymous"></script>

<script>
    $(document).ready(function(){
            $('#logout').click(function (){
                $.get('/apis/v1/users/logout/', {}, function() {
                location.reload();
                });
            });

            $('#search').click(function(){
            var username = $('#searchUserName').val();
            var followeesIds = "{{followees_ids}}";
            $.get("{% url 'apis_v1_user_get' %}", {'username' :username}, function(obj){
                $('#searchResult').html(obj.data.username);
                var $searchRelationButton = $('#searchFollow button');
                $searchRelationButton.data('user-id', obj.data.id);

                console.log(username)
                console.log(obj.data.id)
                console.log(followeesIds)
                console.log(followeesIds.indexOf(obj.data.id))

                if (followeesIds.indexOf(obj.data.id) > -1){
                    $searchRelationButton.removeClass('follow');
                    $searchRelationButton.addClass('unfollow');
                    $searchRelationButton.html('언팔로우');
                } else {
                    $searchRelationButton.removeClass('unfollow');
                    $searchRelationButton.addClass('follow');
                    $searchRelationButton.html('팔로우');
                }
                $('#searchFollow').show();
            }).fail(function(data){
                $('#searchResult').html(data.responseJSON.message);
            });
        });


        $('body').delegate('.follow', 'click', function(e){
            var userId = $(e.currentTarget).data('user-id');
            $.post("{% url 'apis_v1_relation_create' %}", {id: userId}, function(){
                location.reload();
            }).fail(function(data){
                alert(data.responseJSON.message);
            });
        });

        $('body').delegate('.unfollow', 'click', function(e){
            var userId = $(e.currentTarget).data('user-id');
            $.post("{% url 'apis_v1_relation_delete' %}", {id: userId}, function(){
                location.reload();
            }).fail(function(data){
                alert(data.responseJSON.message);
            });
        });
    });

</script>

{% endblock %}